### ISSUE TITLE
Parse errors in generated _form.php and _search.php (PHP Parse error:  syntax error, unexpected T_ECHO)

### ISSUE THREAD

**Issue by motin** [schmunk42/gii-template-collection#9] opened 2013-03-11 10:23 UTC
To reproduce: Generate FullCrud views and see how lines like "<?php echo echo ..." gets generated in _form.php and _search.php

Locally worked around by removing the extra echos from the _form.php and _search.php templates, but not sure if this is the best solution (why does generateActiveLabel prefix it's parent class method with echo?)

**Comment by motin** [comment] 2013-03-11 10:35
Ironically, I see that this stems partly (at least _search.php) from a pr I submitted to thyseus branch: https://github.com/thyseus/gii-template-collection/commit/f8ab9152546e8e7da762b95ff04d8300d78c7096 :)

**Comment by schmunk42** [comment] 2013-03-11 10:50
Ahhhh, thank you! 

I talked with @thyseus about this issue and was clueless at first sight, because it worked for me, but not for him.
But now I know why - at least I hope so ... you're using the `default` template for CRUDs, right?

I created another template, called `slim` and wasn't using the `default` anymore - so I never experienced the error.
Could you try the `slim` template (which is much nicer, btw) and report if it works?

I removed the `echo` from my templates, because they were too inflexible, when using widgets as input elements.

Will also try to reproduce the issue...

**Comment by motin** [comment] 2013-03-11 11:54
True, default templates are used. Slim template depends on gii-template-collection phundament boilerplate?

**Comment by schmunk42** [comment] 2013-03-11 13:41
`echo`s should be fixed by https://github.com/schmunk42/gii-template-collection/commit/6fc1cf2a94401d9357fbaa256887fc79c413bad0

I enabled the 'slim' templates by default now.

They just depend on yii-bootstrap (and echosen and select2 if you use these plugins), not Phundament itself.

Is yii-bootstrap a blocker for you? If not, please let me know about any errors including the CRUDs into a custom application.

**Closed as completed by schmunk42** 2013-03-11 13:41 UTC

**Comment by motin** [comment] 2013-03-12 13:38
> Could you try the slim template (which is much nicer, btw) and report if it works?

It works :)
